name: Format and test code with uv

on: 
  push:
    branches:
      - beta

jobs:
  lint-format-and-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pyronext
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv python install 3.13
          uv run -m ensurepip --upgrade
          uv run -m pip install --upgrade pip
          uv tool install pytest
          uv run -m pip install pytest pytest-asyncio
          uv lock --upgrade

      - name: Run ruff to lint and format code
        run: |
          uv tool run ruff check . --exit-zero
          uv tool run ruff format .
          git add -u

      - name: Commit and push changes
        run: |
          git config --global user.name "5hojib"
          git config --global user.email "hello@shojib.bd"
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "format: with ruff [no ci]" --signoff
            git push origin ${{ github.ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}

      - name: Run tests
        run: uv run -m pytest
        continue-on-error: true
